### ISSUE TITLE
#TK27 PANEL CONTROL ADMINISTRADOR / PRODUCTOS NUEVOS

### ISSUE THREAD

**Issue by dalmaponce** [G10-ISPC/RICCO-2024#18]
#HUC7 Como vendedor/Administrador, quiero poder añadir nueva información de hamburguesas (nombre, descripción, precio, foto) para actualizar el catálogo de productos.

**Comment by MelisaSG** [comment]
Se cierra issue sin poder terminar la parte de edicion de productos y subida de imagen. El resto queda realizado
